#!/bin/sh

echo "
  \set AUTOCOMMIT on
  CREATE USER ${BIDB_USER} PASSWORD '$(cat $BIDB_PASSWORD_FILE)';
  CREATE DATABASE ${BIDB_DB};
  GRANT ALL PRIVILEGES ON DATABASE ${BIDB_DB} TO ${BIDB_USER};
" | psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"
