#!/bin/sh

echo "
  \set AUTOCOMMIT on
  CREATE USER ${BI_USER} PASSWORD '$(cat $BI_PASSWORD_FILE)';
  CREATE DATABASE ${BI_DB};
  GRANT ALL PRIVILEGES ON DATABASE ${BI_DB} TO ${BI_USER};
" | psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"
