# Generated by Django 4.0.4 on 2022-06-01 11:25

from django.db import migrations, models
from typing import List, Any


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name="SalesCreate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.TextField()),
                ("quantity", models.TextField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "sales",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("order_number", models.TextField()),
                ("quantity", models.TextField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "sales",
                "managed": True,
            },
        ),
    ]
